website/views.py
from flask import Blueprint, render_template, jsonify,request,flash, redirect, url_for
from flask_login import  login_required, current_user
from .models import import_ratings_csv
from website import db
from website.models import Movie, User, Rating, Link, Tag
from website.search import search_title

from website.keras import recommend_movies_keras
from website.knn import recommend_movies_knn,recommend_movies_knn_User

from website.cosine import recommend_movies_cosine,recommend_movies_cosine_User
from website.hybrid import recommend_movies_hybrid_User
from flask.globals import current_app
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_paginate import Pagination, get_page_parameter
import json



views = Blueprint('views',__name__)

@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)





@views.route('/rated_movies')
@login_required
def rated_movies():
    rated_movies = db.session.query(Movie, Rating,Link).join(Rating, Movie.id == Rating.movie_id).join(Link, Movie.id == Link.movie_id).filter(Rating.user_id == current_user.id).all()

    return render_template("rated_movies.html", rated_movies=rated_movies, user=current_user)



@views.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    user_ratings = Rating.query.filter_by(user_id=current_user.id).all()
    user_ratings = {r.movie_id: r.rating for r in user_ratings}
    if request.method == 'POST':
        title = request.form.get('title')
        with current_app.app_context():
            movie_df = search_title(title)
        return render_template('search.html',column_names=movie_df.columns.values, row_data=list(movie_df.values.tolist()),link_column="movie_id", zip=zip,user_ratings=user_ratings,title=title, user=current_user)


        
    

@views.route('/recommend', methods=['GET', 'POST'])
@login_required
def recommend():
    user_ratings = Rating.query.filter_by(user_id=current_user.id).all()
    user_ratings = {r.movie_id: r.rating for r in user_ratings}
    movieTitle = None
    
    if request.method == 'POST':
        title = request.form.get('title')
        recommend_type = request.form.get('recommend_type')
        recommend_type_button = request.form.get('recommend_type_button')
        if not title:
            if recommend_type_button == "KNNUser":
                movie_df, _, _ = recommend_movies_knn_User(user_id=current_user.id)
                return render_template('recommend.html',column_names=movie_df.columns.values, row_data=list(movie_df.values.tolist()),link_column="movie_id", zip=zip,movieTitle=movieTitle,user_ratings=user_ratings,selectedRecommendSystem=recommend_type, user=current_user)
            elif recommend_type_button == "CosineUser":
                movie_df, _ = recommend_movies_cosine_User(user_id=current_user.id)
                return render_template('recommend.html',column_names=movie_df.columns.values, row_data=list(movie_df.values.tolist()),link_column="movie_id", zip=zip,movieTitle=movieTitle,user_ratings=user_ratings,selectedRecommendSystem=recommend_type, user=current_user)
            elif recommend_type_button == "KerasUser":
                movie_df, _, _= recommend_movies_keras(user_id=current_user.id)
                return render_template('recommend.html',column_names=movie_df.columns.values, row_data=list(movie_df.values.tolist()),link_column="movie_id", zip=zip,movieTitle=movieTitle,user_ratings=user_ratings,selectedRecommendSystem=recommend_type, user=current_user)
            elif recommend_type_button == "HybridUser":
                movie_df= recommend_movies_hybrid_User(user_id=current_user.id)
                return render_template('recommend.html',column_names=movie_df.columns.values, row_data=list(movie_df.values.tolist()),link_column="movie_id", zip=zip,movieTitle=movieTitle,user_ratings=user_ratings,selectedRecommendSystem=recommend_type, user=current_user)
            
            flash("Please type in a movie title",category='error')
            return render_template('recommend.html',movieTitle=movieTitle,user_ratings=user_ratings)
        else:
            with current_app.app_context():
                if not recommend_type:
                    flash("Please select a recommendation algorithm.",category='error')
                    return render_template('recommend.html',movieTitle=movieTitle,user_ratings=user_ratings)
                
                elif recommend_type == 'Cosine':
                    movie_df,movieTitle, _ = recommend_movies_cosine(title)
                elif recommend_type == 'KNN':
                    movie_df,movieTitle, _ = recommend_movies_knn(title)
                
                
            return render_template('recommend.html',column_names=movie_df.columns.values, row_data=list(movie_df.values.tolist()),link_column="movie_id", zip=zip,movieTitle=movieTitle,user_ratings=user_ratings,selectedRecommendSystem=recommend_type, user=current_user)
    
    return render_template('recommend.html',movieTitle=movieTitle,user_ratings=user_ratings)
    


@views.route('/user', methods=['GET', 'POST'])
def user():
    if request.method == 'GET':
        all_users = User.query.all()
        return render_template('user.html', all_users=all_users)
    if request.method == 'POST':
        all_users = User.query.all()
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already used',category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.',category='error')   
        elif len(first_name) < 2:
            flash('First name must be greater than 1 characters.',category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.',category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.',category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            all_users = User.query.all()
            return render_template('user.html', all_users=all_users)
        
    return render_template("user.html", all_users=all_users)

@views.route('/update', methods=['POST', 'GET'])
def update():
    if request.method == 'POST':
        user_data = User.query.get(request.form.get('id'))
        if user_data:
            new_email = request.form['email']
            existing_user = User.query.filter_by(email=new_email).first()
            if existing_user and existing_user.id != user_data.id:
                flash('Email is already being used by another account', category='error')
            else:
                user_data.first_name = request.form['firstName']
                user_data.email = new_email
                db.session.commit()
        return redirect(url_for('views.user'))
    return redirect(url_for('views.user'))

@views.route('/delete/<int:user_id>', methods=['POST'])
def delete(user_id):
    user = User.query.get(user_id)
    if user:
        Rating.query.filter_by(user_id=user_id).delete()
        db.session.delete(user)
        db.session.commit()
    return redirect(url_for('views.user'))

@views.route('/movies', methods=['GET', 'POST'])
def movie():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = 100
    offset = (page - 1) * per_page
    

    if request.method == 'GET':
        
        movies = Movie.query.offset(offset).limit(per_page).all()
        total = Movie.query.count()
        pagination = Pagination(page=page, per_page=per_page, total=total, css_framework="bootstrap5")

        for movie in movies:
            links = Link.query.filter_by(movie_id=movie.id).all()
            movie.links = links

        return render_template('movies.html', all_movies=movies, pagination=pagination)
    
    if request.method == 'POST':

        movies = Movie.query.offset(offset).limit(per_page).all()
        total = Movie.query.count()

        for movie in movies:
            links = Link.query.filter_by(movie_id=movie.id).all()
            movie.links = links

        title = request.form.get('title')
        genreArray = json.loads(request.form.get('genreArray', '[]'))
        genre = "|".join(genreArray)
        
        movie = Movie.query.filter_by(title=title).first()
        if movie:
            flash('Movie already added',category='error')
        
        else:
            new_movie = Movie(title=title, genre=genre)
            db.session.add(new_movie)
            db.session.commit()
            flash('Movie added!', category='success')

            movies = Movie.query.offset(offset).limit(per_page).all()
            total = Movie.query.count()
            pagination = Pagination(page=page, per_page=per_page, total=total, css_framework="bootstrap5")

            for movie in movies:
                links = Link.query.filter_by(movie_id=movie.id).all()
                movie.links = links

        return render_template('movies.html', all_movies=movies, pagination=pagination)
        
    return render_template('movies.html', all_movies=movies, pagination=pagination)
    
@views.route('/deleteMovie/<int:movie_id>', methods=['POST'])
def deleteMovie(movie_id):
    movie = Movie.query.get(movie_id)
    if movie:
        Rating.query.filter_by(movie_id=movie_id).delete()
        Tag.query.filter_by(movie_id=movie_id).delete()
        db.session.delete(movie)
        db.session.commit()
    return redirect(request.referrer)

@views.route('/updateMovie', methods=['POST'])
def updateMovie():

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device=width, initial-scale=1" />  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    
    <style>
      body
       {
        background-color: #1D2D44;
        padding-bottom: 70px;
      }
      .customNavbar{
        background-color: #7892B4;
      }
      </style>
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    {% if current_user.is_authenticated %}
    <nav class="navbar customNavbar navbar-expand-lg navbar-dark">
      <div class="container">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" id="home" href="/">Home</a>
          </li>
        </ul>
        <form action="{{ url_for('views.search') }}" method="POST" class="mx-auto">
          <div style="display: flex;">
            <input type="text" class="form-control" name="title" placeholder="Search movies" aria-label="Search movies">
            <button type="submit" class="btn "><i class="fa fa-search"></i></button>
        </div>
        </form>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-item nav-link" id="recommend" href="/recommend">Recommend</a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" id="myRatedMovies" href="/rated_movies">My Rated Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" id="manageUsers" href="/user">Manage Users</a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" id="manageMovies" href="/movies">Manage Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="logout" href="/logout">Logout</a>
          </li>
        </ul>
        </div>
      </div>
      
      </nav>
    {%endif%}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error'%}
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {%else%}
        <div class="alert alert-success alert-dismissable fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {%endif%}
        {%endfor%}
    {%endif%}
    {%endwith%}
   
        {% block content %}
        {% endblock %}
  
    <footer class="bg-dark text-center text-light fixed-bottom">
      <div class="container p-4">
        <p class="lead">Copyright &copy; 2023 VilniusTech</p>
      
      </div>
    </footer>
  
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  
  </body>
</html>

website/templates/login.html
{% extends "base.html" %}{% block title %}Login{% endblock %} {%block content %}
<style>
  .customCard {
    background-color: #2f4e7b;
    border-radius: 30px;
    width: 75%;
    
    margin: auto;
  }
  .customButton {
    background-color: #7892b4;
    width: 100px;
    margin-left: 30px;
    margin-right: 30px;
    margin-top: 5px;
    margin-bottom: 5px;
  }
  .customForm {
    width: 75%;
    height: auto;
    margin: auto;
    
  }
  
</style>
<div class="container">
  <img class="img-fluid w-25 d-none d-md-block mx-auto pt-2" src="static/movie.svg" alt="">
<form method="POST">
  <div class="card customCard text-light mt-5">
    <div class="card-body text-center">
      <h3 align="center">Log in</h3>
      <div class="form customForm form-group mb-3 mt-3 ">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group customForm">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn customButton text-light">Login</button>
      <a class = "btn customButton text-light" href="/sign-up">Sign Up</a>
      
    </div>
  </div>
</form>
</div>

{% endblock %}

website/templates/movies.html
{% extends "base.html" %}

{% block content %}
<style>
    .pagination .page-item .page-link {
        background-color: #343a40;
        color: #fff;
    }
    .pagination .page-item.active .page-link {
        background-color: #17a2b8;
        border-color: #17a2b8;
    }
    
</style>

<div class="container">
    <div class="container text-light">
    <h2> <b>Manage movies </b><button type="button" class="btn btn-success " data-toggle="modal"
        data-target="#mymodal">Add new</button></h2>
    </div>
    <table class="table text-light">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Genre</th>
                <th>Links</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in all_movies %}
                <tr>
                    <td>{{ movie.id }}</td>
                    <td>{{ movie.title }}</td> 
                    <td>{{ movie.genre }}</td>
                    <td>
                        {% for link in movie.links %}
                        <a href="https://www.imdb.com/title/tt{{ link.imdb_id }}/" target="_blank">IMDB</a>
                        <a href="https://www.themoviedb.org/movie/{{ link.tmdb_id }}?language=en-US" target="_blank">TMDB</a>
                        {% endfor %}
                    </td>
                    <td>
                        <a href="/updateMovie/{{movie.id}}" class="btn btn-sm btn-primary" data-toggle="modal"
                                    data-target="#modaledit{{movie.id}}">Edit</a>
                                    <form action="{{ url_for('views.deleteMovie', movie_id=movie.id) }}" method="POST"
                                    style="display: inline;">
                                    <button class="btn btn-sm btn-danger" type="button"
                                        onclick="confirmDelete('{{ movie.id }}')">Delete</button>
                                </form>
                    </td>
                </tr>
                <div id="modaledit{{movie.id}}" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Update Information</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{ url_for('views.updateMovie') }}" method="POST">
                                            <div class="form-group">
                                                <label>Movie Title:</label>
                                                <input type="hidden" name="id" value="{{movie.id}}">
                                                <input type="text" class="form-control" name="title" id="title"
                                                    value="{{movie.title}}">
                                            </div>
                                            <div class="form-group">
                                                <label>Genre:</label>
                                                <input type="text" class="form-control" name="genre" id="genre"
                                                    value="{{movie.genre}}">
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-primary" type="sbumit">Update</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-center my-4">
        {{ pagination.links }}
    </div>
    <div id="mymodal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add movie</h4>
                </div>
                <form method="POST" id="addMovieForm">
                    <div class="modal-body">
                        <div class="form-group customForm form-group mt-3 mb-1 ">
                            <label for="title">Title</label>
                            <input type="title" class="form-control" id="title" name="title"
                                placeholder="Enter title" />
                        </div>
                        <div class="form-group mb-1">
                            <label for="genre">Genre</label>
                            <div id="genres">
                                <select class="form-control mb-1" name="genre" onchange="updateSelectedGenres(event)" data-previous-value="Action">
                                    <option value="Action">Action</option>
                                    <option value="Adventure">Adventure</option>
                                    <option value="Animation">Animation</option>
                                    <option value="Biography">Biography</option>
                                    <option value="Comedy">Comedy</option>
                                    <option value="Crime">Crime</option>
                                    <option value="Documentary">Documentary</option>
                                    <option value="Drama">Drama</option>
                                    <option value="Family">Family</option>
                                    <option value="Fantasy">Fantasy</option>
                                    <option value="Film-Noir">Film-Noir</option>
                                    <option value="History">History</option>
                                    <option value="Horror">Horror</option>
                                    <option value="Music">Music</option>
                                    <option value="Musical">Musical</option>
                                    <option value="Mystery">Mystery</option>
                                    <option value="Romance">Romance</option>
                                    <option value="Sci-Fi">Sci-Fi</option>
                                    <option value="Sport">Sport</option>
                                    <option value="Thriller">Thriller</option>
                                    <option value="War">War</option>
                                    <option value="Western">Western</option>
                                </select>
                            </div>
                            <button type="button" class="btn btn-sm btn-primary mt-2" onclick="addGenre()">Add more genres</button>
                        </div>
                        <br />
                        <button type="submit" class="btn customButton text-light btn-success" onclick="submitForm(event)">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function confirmDelete(movieId) {
        if (confirm("Are you sure you want to delete this movie?")) {
            // If the movie confirms, submit the delete form
            document.querySelector(`form[action='/deleteMovie/${movieId}']`).submit();
        }
    }
    function addGenre() {
        const genresDiv = document.getElementById("genres");
        const select = document.createElement("select");
        select.classList.add("form-control", "mb-1");
        select.name = "genre";
    
        const genres = ['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'Western'];
    
        genres.forEach(genre => {
            const option = document.createElement("option");
            option.value = genre;
            option.innerText = genre;
            select.appendChild(option);
        });
    
        select.addEventListener('change', updateSelectedGenres); // Add this line
    
        genresDiv.appendChild(select);
    }
    const selectedGenres = new Set(["Action"]);

    function updateSelectedGenres(e) {
        const genre = e.target.value;
        const previousGenre = e.target.getAttribute('data-previous-value');
    
        if (previousGenre) {
            selectedGenres.delete(previousGenre);
        }
    
        if (!selectedGenres.has(genre)) {
            selectedGenres.add(genre);
        }
    
        e.target.setAttribute('data-previous-value', genre);
    }

function submitForm(e) {
    e.preventDefault();

    const genreArray = Array.from(selectedGenres); // Convert the Set to an array

    const form = document.getElementById("addMovieForm");
    const formData = new FormData(form);
    formData.append("genreArray", JSON.stringify(genreArray));

    fetch(form.action, {
        method: "POST",
        body: formData,
    })
        .then((response) => {
            if (response.ok) {
                location.reload();
            } else {
                alert("Error adding movie");
            }
        })
        .catch((error) => {
            console.error("Error:", error);
        });
}

</script>
{% endblock %}

website/templates/user.html
{% extends "base.html" %}{% block title %}Home{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2 class="text-white"> Manage Users</h2>
                    <button type="button" class="btn btn-success mb-2 " data-toggle="modal" data-target="#mymodal">Add new</button>

                <table class="table table text-light mb-4">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>First Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in all_users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>
                                <a href="/update/{{user.id}}" class="btn btn-sm btn-primary" data-toggle="modal"
                                    data-target="#modaledit{{user.id}}">Edit</a>
                                <form action="{{ url_for('views.delete', user_id=user.id) }}" method="POST"
                                    style="display: inline;">
                                    <button class="btn btn-sm btn-danger" type="button"
                                        onclick="confirmDelete('{{ user.id }}')">Delete</button>
                                </form>
                            </td>
                        </tr>
                        <div id="modaledit{{user.id}}" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Update Information</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{ url_for('views.update') }}" method="POST">
                                            <div class="form-group">
                                                <label>Name:</label>
                                                <input type="hidden" name="id" value="{{user.id}}">
                                                <input type="text" class="form-control" name="firstName" id="firstName"
                                                    value="{{user.first_name}}">
                                            </div>
                                            <div class="form-group">
                                                <label>Email:</label>
                                                <input type="text" class="form-control" name="email" id="email"
                                                    value="{{user.email}}">
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-primary mt-2" type="sbumit">Update</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div id="mymodal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add User</h4>
                        </div>
                        <form method="POST">
                            <div class="modal-body">
                                
                                <div class="form-group customForm form-group mt-3 mb-1 ">
                                    <label for="email">Email Adress</label>
                                    <input type="email" class="form-control" id="email" name="email"
                                        placeholder="Enter email" />
                                </div>
                                <div class="form-group customForm mb-1">
                                    <label for="firstName">First Name</label>
                                    <input type="text" class="form-control" id="firstName" name="firstName"
                                        placeholder="Enter first name" />
                                </div>
                                <div class="form-group customForm mb-1">
                                    <label for="password1">Password</label>
                                    <input type="password" class="form-control" id="password1" name="password1"
                                        placeholder="Enter password" />
                                </div>
                                <div class="form-group customForm mb-1">
                                    <label for="password2">Password (Confirm)</label>
                                    <input type="password" class="form-control" id="password2" name="password2"
                                        placeholder="Confirm password" />
                                </div>
                                <br />
                                <button type="submit" class="btn customButton text-light btn-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</div>
</div>
</div>
</div>
<script>
    function confirmDelete(userId) {
        if (confirm("Are you sure you want to delete this user?")) {
            document.querySelector(`form[action='/delete/${userId}']`).submit();
        }
    }
</script>
{% endblock %}